config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('service_app.urls', 'service_app'), namespace='service_app')),
    path('blog_app/', include(('blog_app.urls', 'blog_app'), namespace='blog_app')),
    path('user_app/', include(('user_app.urls', 'user_app'), namespace='user_app')),

]

service_app/urls.py
from django.urls import path
from service_app import views as v
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', v.IndexListView.as_view(), name='index'),

    path('clients_list/', v.ClientsListVew.as_view(), name='clients_list'),
    path('view_client_<int:pk>/', v.ClientView.as_view(), name='view_client'),
    path('create_client/', v.ClientCreateView.as_view(), name='create_client'),
    path('update_client_<int:pk>/', v.ClientUpdateView.as_view(), name='update_client'),
    path('delete_client_<int:pk>/', v.ClientDeleteView.as_view(), name='delete_client'),

    path('create_mailer/', v.MailingCreateView.as_view(), name='create_mailer'),
    path('edit_mailer_<int:pk>/', v.MailingUpdateView.as_view(), name='edit_mailer'),
    path('view_mailer_<int:pk>/', v.MailingView.as_view(), name='view_mailer'),
    path('delete_mailer_<int:pk>/', v.MailingDeliteView.as_view(), name='delete_mailer'),
    path('change_status_mailer_<int:pk>/', v.change_mailing_status, name='status_mailer'),

    path('view_logs', v.LogsListView.as_view(), name='logs_view'),    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service_app/models.py
from django.db import models


class Clients(models.Model):
    email = models.EmailField(
        verbose_name='Электронная почта',
        unique=True,
        db_index=True)
    name = models.CharField(
        max_length=100,
        verbose_name='Имя'
    )
    surame = models.CharField(
        max_length=100,
        verbose_name='Фамилия'
    )
    fathers_name = models.CharField(
        max_length=100,
        verbose_name='Отчество',
        null=True,
        blank=True
    )
    comment = models.TextField(
        verbose_name='Комментарий')
    client_author = models.CharField(
        max_length=100,
        verbose_name='Автор',
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    def __str__(self) -> str:
        return f'{self.name} {self.surame} ({self.email})'


class Mailing(models.Model):
    mailing_time = models.TimeField(
        verbose_name='Время рассылки',
        blank=True,
        null=True
    )
    mailing_period = models.CharField(
        max_length=50,
        verbose_name='Период рассылки',
        blank=True,
        null=True
    )
    mailing_status = models.CharField(
        max_length=50,
        verbose_name='Статус рассылки',
        choices=(
            ('CNL', 'Завершена'),
            ('CRT', 'Создана'),
            ('ACT', 'Запущена')
        )
    )
    mailing_day = models.CharField(
        verbose_name='День рассылки',
        blank=True,
        null=True,
        choices=(
            (None, 'Каждый день'),
            ('mon', 'Понедельник'),
            ('tue', 'Вторник'),
            ('wed', 'Среда'),
            ('thu', 'Четверг'),
            ('fri', 'Пятница'),
            ('sat', 'Суббота'),
            ('sun', 'Воскресенье')
        )
    )
    mailing_day_of_month = models.IntegerField(
        null=True,
        blank=True,
        verbose_name='День в месяце'
    )

    mail_header = models.CharField(
        max_length=150,
        verbose_name='Тема письма',
        unique=True
    )
    mail_message = models.TextField(
        verbose_name='Текст письма'
    )

    recepient = models.ManyToManyField(
        to=Clients,
        related_name='recepirnts',
        blank=True,
        verbose_name='Адресант'
    )
    mailing_author = models.CharField(
        max_length=100,
        verbose_name='Автор',
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

    def __str__(self):
        return f'{self.mail_header}, {self.mailing_status}'


class Logs(models.Model):
    mail_header = models.CharField(
        verbose_name='Рассылка',
        default=None,
        null=True
    )
    email = models.CharField(
        verbose_name='Электронная почта',
        default=None,
        null=True
    )
    date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Последняя попытка'
    )
    status = models.CharField(
        max_length=50,
        verbose_name='Статус попытки'
    )
    response = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name='Ответ почтового сервера'
    )
    log_author = models.CharField(
        max_length=100,
        verbose_name='Автор',
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

service_app/forms.py
from service_app import models as m
from django import forms


class MailerForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['recepient'].queryset = m.Clients.objects.filter(client_author=user)
        print(m.Clients.objects.filter(client_author=user))

    mailing_time = forms.TimeField(label='Время рассылки', required=False,
                                   widget=forms.TimeInput(attrs={'class': 'same-widht'}))
    mailing_period = forms.ChoiceField(label='Период рассылки', required=False, choices=(
        (None, 'Весь день'),
        ('PD', 'Раз в сутки'),
        ('PW', 'Раз в неделю'),
        ('PM', 'Раз в месяц')), widget=forms.Select(attrs={'class': 'same-widht'}))
    mailing_status = forms.ChoiceField(
        label='Статус рассылки',
        initial=('CRT', 'Создана'),
        choices=(
            ('CNL', 'Завершена'),
            ('CRT', 'Создана'),
            ('ACT', 'Запущена')),
        widget=forms.Select(
            attrs={
                'class': 'same-widht'
            }
        )
    )
    mailing_day = forms.ChoiceField(
        label='День рассылки',
        required=False,
        choices=(
            (None, 'Каждый день'),
            ('mon', 'Понедельник'),
            ('tue', 'Вторник'),
            ('wed', 'Среда'),
            ('thu', 'Четверг'),
            ('fri', 'Пятница'),
            ('sat', 'Суббота'),
            ('sun', 'Воскресенье')),
        widget=forms.Select(
            attrs={
                'class': 'same-widht'
            }
        )
    )
    mailing_day_of_month = forms.IntegerField(
        max_value=31,
        label='День в месяце',
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'same-widht'
            }
        )
    )
    mail_header = forms.CharField(
        label='Тема письма',
        widget=forms.TextInput(
            attrs={
                'class': 'same-widht'
            }
        )
    )
    mail_message = forms.CharField(
        label='Текст письма',
        widget=forms.Textarea(
            attrs={
                'class': 'same-widht same-height'
            }
        )
    )
    recepient = forms.ModelMultipleChoiceField(
        label='Адресанты',
        queryset=m.Clients.objects.all(),
        widget=forms.SelectMultiple(
            attrs={
                'class': 'same-widht'
            }
        )
    )

    class Meta:
        model = m.Mailing
        exclude = ['mailing_author']


class ClientsForm(forms.ModelForm):
    email = forms.CharField(
        max_length=200,
        label='Электронная почта',
        widget=forms.TextInput(
            attrs={
                'class': 'same-widht'
            }
        )
    )
    name = forms.CharField(
        max_length=200,
        label='Имя',
        widget=forms.TextInput(
            attrs={
                'class': 'same-widht'
            }
        )
    )
    surame = forms.CharField(
        max_length=200,
        label='Фамилия',
        widget=forms.TextInput(
            attrs={
                'class': 'same-widht'
            }
        )
    )
    fathers_name = forms.CharField(
        max_length=200,
        label='Отчество',
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'same-widht'
            }
        )
    )
    comment = forms.Field(
        label='Комментарий',
        widget=forms.Textarea(
            attrs={
                'class': 'same-widht same-height'
            }
        )
    )

    class Meta:
        model = m.Clients
        exclude = ['client_author']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data['email']
        if '@' not in email and '.' not in email:
            raise forms.ValidationError('Это не эмейл, чувак')
        return email

service_app/views.py
import random
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic as g

from service_app import models as m
from blog_app import models as blog_models
from service_app import forms as f
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

class IndexListView(g.ListView):
    model = m.Mailing
    template_name = 'service_app/index_list.html'
    context_object_name = 'context'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mailings_count'] = len(m.Mailing.objects.filter(mailing_author=self.request.user))
        context['active_mailings_count'] = len(
            m.Mailing.objects.filter(mailing_status='ACT').filter(mailing_author=self.request.user))
        context['unique_clients'] = len(m.Clients.objects.filter(client_author=self.request.user))
        context['random_post'] = self.get_random_records()
        return context

    @staticmethod
    def get_random_records():
        # Получаем общее количество записей в модели
        total_records = blog_models.Blog.objects.count()

        # Если в модели менее трех записей, выбираем все записи
        if total_records <= 3:
            random_records = blog_models.Blog.objects.all()
        else:
            # Генерируем случайные индексы записей
            random_indexes = random.sample(range(total_records), 3)

            # Выбираем три записи с соответствующими индексами
            random_records = blog_models.Blog.objects.filter(pk__in=random_indexes)
        return random_records

    def get_queryset(self):
        queryset = super().get_queryset()
        user = self.request.user
        if user.is_authenticated:
            if user.is_staff or user.is_superuser:
                pass
            else:
                queryset = queryset.filter(mailing_author=self.request.user)
        return queryset


class ClientsListVew(g.ListView):
    model = m.Clients
    template_name = 'service_app/clients/clients_list.html'
    context_object_name = 'context'

    def get_queryset(self):
        queryset = super().get_queryset()
        new_query = queryset.filter(client_author=self.request.user)
        return new_query


class ClientView(g.DetailView):
    model = m.Clients
    template_name = 'service_app/clients/clients_view.html'
    context_object_name = 'context'


class ClientCreateView(LoginRequiredMixin, g.CreateView):
    model = m.Clients
    template_name = 'service_app/clients/clients_create.html'
    success_url = reverse_lazy('service_app:index')
    form_class = f.ClientsForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["editing"] = False
        return context

    def form_valid(self, form):
        if form.is_valid():
            w = form.save(commit=False)
            w.client_author = self.request.user
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, g.UpdateView):
    model = m.Clients
    template_name = 'service_app/clients/clients_create.html'
    form_class = f.ClientsForm
    success_url = reverse_lazy('service_app:index')
    context_object_name = 'context'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["editing"] = True
        return context

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
        return super().form_valid(form)


class ClientDeleteView(LoginRequiredMixin, g.DeleteView):
    model = m.Clients
    template_name = "service_app/clients/clients_delete.html"
    context_object_name = 'context'
    success_url = reverse_lazy('service_app:clients_list')

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset.filter(pk=self.kwargs['pk'])
        return queryset


class MailingCreateView(LoginRequiredMixin, g.CreateView):
    model = m.Mailing
    template_name = "service_app/mailing/mailing_create.html"
    success_url = reverse_lazy("service_app:index")
    form_class = f.MailerForm
    context_object_name = 'context'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["editing"] = False
        return context

    def form_valid(self, form):
        if form.is_valid():
            w = form.save(commit=False)
            w.mailing_author = self.request.user
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        # Добавление дополнительных аргументов для формы
        kwargs['user'] = self.request.user.email
        return kwargs


class MailingUpdateView(LoginRequiredMixin, g.UpdateView):
    model = m.Mailing
    template_name = "service_app/mailing/mailing_create.html"
    success_url = reverse_lazy("service_app:index")
    form_class = f.MailerForm
    context_object_name = 'context'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["clients"] = m.Clients.objects.all()
        context["editing"] = True
        return context

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # Передача пользователя в `kwargs`
        return kwargs


class MailingView(g.DetailView):
    model = m.Mailing
    template_name = "service_app/mailing/mailing_view.html"
    context_object_name = 'context'


class MailingDeliteView(LoginRequiredMixin, g.DeleteView):
    model = m.Mailing
    template_name = "service_app/mailing/mailing_delete.html"
    context_object_name = 'context'
    success_url = reverse_lazy('service_app:index')

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset.filter(pk=self.kwargs['pk'])
        return queryset


# @permission_required('service_app.change_blog')
def change_mailing_status(request, pk):
    mailing = get_object_or_404(m.Mailing, pk=pk)
    if mailing.mailing_status == 'ACT':
        mailing.mailing_status = 'CNL'
    else:
        mailing.mailing_status = 'ACT'
    mailing.save()
    return redirect(reverse('service_app:index'))


class LogsListView(g.ListView):
    model = m.Logs
    template_name = 'service_app/logs_list.html'
    context_object_name = 'logs'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        user = self.request.user
        if user.is_authenticated:
            queryset = queryset.filter(log_author=user.email)
        return queryset

service_app/templates/service_app/clients/clients_create.html
{% extends 'service_app/base.html' %}
{% load static %}


{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/my_styles.css' %}">
    
    <h1>Создание нового клиента</h1>
    <p>Для создания нового клиента, пожалуйста, заполните форму ниже:</p>
    <div class="container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="text-center" style="position: relative; left: 18%; top: 10mm;">
                {% for f in form %}
                <div class="col-7 row mb-4" style="font-size: 5mm;">
                    <div class="col text-start" style="position: relative; left: 25mm;"><label class="" for="{{ f.id_for_label }}">{{ f.label }}</label></div>
                    <div class="col text-end" style="width: 10cm; z-index: 100;">{{f}}</div>            
                </div>
                <div class="form-error">{{ f.errors }}</div>
                {% endfor %}
                <div class="text-start" style="position: relative; left: 10cm;">
                {% if editing %}
                    <button type="submit" class="btn btn-primary" enp>Изменить запись</button>
                {% else %}
                    <button type="submit" class="btn btn-primary" enp>Добавить запись</button>
                {% endif %}
                </div>
            </div>
            
        </form>
    </div>
    
{% endblock %}
    

service_app/templates/service_app/clients/clients_delete.html
{% extends 'service_app/base.html' %}


{% block content %}
<style>
    mono {font-family: monospace;}
</style>
<form method="post">
    {% csrf_token %}
    <div class="text-center" style="position: relative; top: 1cm;">
        <h1>Вы действительно хотите удалить адресанта:</h1>
        <mono style="font-size: 12mm;">{{ context.name }} {{context.surame}}</mono>
        <br><mono style="font-size: 10mm;"">{{ context.email }}</mono>

        {{ form }}

        <div class="col-3 row" style="position: relative; top: 5mm; left: 185mm;">
            <div class="col">
                <input type="submit" class="btn btn-outline-danger" value="Подтвердить">
            </div>
            <div class="col">
                <a type="button" class="btn btn-outline-warning" href="{% url 'service_app:clients_list' %}">Отмена</a>
            </div>
        </div>
    </div>
</form>
{% endblock content %}

service_app/templates/service_app/clients/clients_list.html
{% extends 'service_app/base.html' %}
{% load static %}
{% block content %}
<h1 class="text-white text-center">Список клиентов</h1>

<div class="container text-center">
    <div class="row" style="position: absolute; left: 30%; top: 20%;">
        {% for c in context %}
        <div class="card text-bg-dark mb-4"
            style="width: 50rem; height: 10rem;">
            <div class="card-body">
                <h4 class="card-title">{{ c.name }} {{ c.surame }}</h4>
                <h5 class="card-title">{{ c.email }}</h5>
                <p class="card-text">{{ c.comment|truncatechars:50 }}</p>
                <a href="{% url 'service_app:view_client' c.pk %}" class="card-link">Просмотр</a>
                <a href="{% url 'service_app:update_client' c.pk %}" class="card-link">Редактировать</a>
                <a href="{% url 'service_app:delete_client' c.pk %}" class="card-link">Удалить</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

service_app/templates/service_app/clients/clients_view.html
{% extends 'service_app/base.html' %}


{% block content %}
{% load paragrapher %}

    <div class="text-center" style="position: relative; top: 5mm;">
        <div class="row">
            <div class="col text-start"><a style="position: relative;" type="button" href="{% url 'service_app:clients_list' %}" class="btn btn-outline-light">Назад</a></div>
            <div class="col-9 text-start"><h1 style="font-size: 12mm;">Просмотр карточкки адресанта: {{ context.first_name }} {{context.last_name}}</h1></div>
        </div>
        <div style="position: relative; top: 10mm;">
        <h4 class="text-start" 
        style="position: relative; top: 5mm; left: 10cm;
        font-size: 8mm;">Имя: <mono style="font-size: 10mm;">{{ context.name }}</mono></h4>
        <h4 class="text-start" 
        style="position: relative; top: 5mm; left: 10cm;
        font-size: 8mm;">Фамилия: <mono style="font-size: 10mm;">{{ context.surame }}</mono></h4>
        
        <h4 class="text-start" 
        style="position: relative; top: 5mm; left: 10cm;
        font-size: 8mm;">Отчество: <mono style="font-size: 10mm;">{{ context.fathers_name|default_if_none:"Не указано" }}</mono></h4>

        <h4 class="text-start" 
        style="position: relative; top: 10mm; left: 10cm;
        font-size: 8mm;">Email: <mono style="font-size: 10mm;">{{ context.email }}</mono></h4>
        
        <p class="text-start"
        style="position: relative; top: 6mm; left: 10cm; right: 10cm;
        font-size: 8mm;">
            <br>Комментарий:
            {% autoescape off %}
                <br><div class="col-8 text-start" style="position: relative; left: 12cm; top: 1cm;
            font-size: 6mm;">{{ context.comment|paragrapher}}</div>
            {% endautoescape %}
        </p>
    </div>
    </div>
{% endblock content %}
    