blog_app/urls.py
from django.urls import path
from blog_app.apps import BlogAppConfig
from blog_app import views as v

app_name = BlogAppConfig.name


urlpatterns = [
    path('all_posts/', v.PostsListView.as_view() , name='all_posts'),
    path('create/', v.PostCreateView.as_view(), name='create'),
    path('<int:pk>/view/', v.PostDetailView.as_view() , name='view'),
    path('<int:pk>/edit/', v.PostUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', v.PostDeleteView.as_view() , name='delete'),
    path('<int:pk>/change_blog_status/', v.change_blog_status , name='change_blog_status'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('service_app.urls', 'service_app'), namespace='service_app')),
    path('blog_app/', include(('blog_app.urls', 'blog_app'), namespace='blog_app')),
    path('user_app/', include(('user_app.urls', 'user_app'), namespace='user_app')),

]

service_app/urls.py
from django.urls import path
from service_app import views as v
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', v.IndexListView.as_view(), name='index'),

    path('clients_list/', v.ClientsListVew.as_view(), name='clients_list'),
    path('view_client_<int:pk>/', v.ClientView.as_view(), name='view_client'),
    path('create_client/', v.ClientCreateView.as_view(), name='create_client'),
    path('update_client_<int:pk>/', v.ClientUpdateView.as_view(), name='update_client'),
    path('delete_client_<int:pk>/', v.ClientDeleteView.as_view(), name='delete_client'),

    path('create_mailer/', v.MailingCreateView.as_view(), name='create_mailer'),
    path('edit_mailer_<int:pk>/', v.MailingUpdateView.as_view(), name='edit_mailer'),
    path('view_mailer_<int:pk>/', v.MailingView.as_view(), name='view_mailer'),
    path('delete_mailer_<int:pk>/', v.MailingDeliteView.as_view(), name='delete_mailer'),
    path('change_status_mailer_<int:pk>/', v.change_mailing_status, name='status_mailer'),

    path('view_logs', v.LogsListView.as_view(), name='logs_view'),    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_app/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from user_app import views as v
from django.views.decorators.cache import cache_page

app_name = 'user_app'

urlpatterns = [
    path('login_user/', cache_page(16*60)(v.UserLoginView.as_view()), name='login_user'),
    path('logout_user/', cache_page(16*60)(LogoutView.as_view()), name='logout_user'),
    path('register_user/', v.RegisterUserView.as_view(), name='register_user'),
    path('confirm_user/', v.ConfirmEmailView.as_view(), name='confirm_user'),
    path('reset_password/', v.reset_password, name='reset_password'),
    path('delete_avatar/', cache_page(16*60)(v.delete_avatar), name='delete_avatar'),
    path('update_user/', v.UpdateProfileView.as_view(), name='update_user'),
    path('profile_view/', cache_page(16*60)(v.ProfileView.as_view()), name='profile_view'),
    path('users_list/', v.UsersListView.as_view(), name='users_list'),
    path('change_profile_status_<int:pk>/', cache_page(16*60)(v.change_profile_status), name='change_profile_status'),
]

service_app/models.py
from django.db import models


class Clients(models.Model):
    email = models.EmailField(
        verbose_name='Электронная почта',
        unique=True,
        db_index=True)
    name = models.CharField(
        max_length=100,
        verbose_name='Имя'
    )
    surame = models.CharField(
        max_length=100,
        verbose_name='Фамилия'
    )
    fathers_name = models.CharField(
        max_length=100,
        verbose_name='Отчество',
        null=True,
        blank=True
    )
    comment = models.TextField(
        verbose_name='Комментарий')
    client_author = models.CharField(
        max_length=100,
        verbose_name='Автор',
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    def __str__(self) -> str:
        return f'{self.name} {self.surame} ({self.email})'


class Mailing(models.Model):
    mailing_time = models.TimeField(
        verbose_name='Время рассылки',
        blank=True,
        null=True
    )
    mailing_period = models.CharField(
        max_length=50,
        verbose_name='Период рассылки',
        blank=True,
        null=True
    )
    mailing_status = models.CharField(
        max_length=50,
        verbose_name='Статус рассылки',
        choices=(
            ('CNL', 'Завершена'),
            ('CRT', 'Создана'),
            ('ACT', 'Запущена')
        )
    )
    mailing_day = models.CharField(
        verbose_name='День рассылки',
        blank=True,
        null=True,
        choices=(
            (None, 'Каждый день'),
            ('mon', 'Понедельник'),
            ('tue', 'Вторник'),
            ('wed', 'Среда'),
            ('thu', 'Четверг'),
            ('fri', 'Пятница'),
            ('sat', 'Суббота'),
            ('sun', 'Воскресенье')
        )
    )
    mailing_day_of_month = models.IntegerField(
        null=True,
        blank=True,
        verbose_name='День в месяце'
    )

    mail_header = models.CharField(
        max_length=150,
        verbose_name='Тема письма',
        unique=True
    )
    mail_message = models.TextField(
        verbose_name='Текст письма'
    )

    recepient = models.ManyToManyField(
        to=Clients,
        related_name='recepirnts',
        blank=True,
        verbose_name='Адресант'
    )
    mailing_author = models.CharField(
        max_length=100,
        verbose_name='Автор',
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

    def __str__(self):
        return f'{self.mail_header}, {self.mailing_status}'


class Logs(models.Model):
    mail_header = models.CharField(
        verbose_name='Рассылка',
        default=None,
        null=True
    )
    email = models.CharField(
        verbose_name='Электронная почта',
        default=None,
        null=True
    )
    date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Последняя попытка'
    )
    status = models.CharField(
        max_length=50,
        verbose_name='Статус попытки'
    )
    response = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name='Ответ почтового сервера'
    )
    log_author = models.CharField(
        max_length=100,
        verbose_name='Автор',
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

service_app/forms.py
from service_app import models as m
from django import forms


class MailerForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['recepient'].queryset = m.Clients.objects.filter(client_author=user)
        print(m.Clients.objects.filter(client_author=user))

    mailing_time = forms.TimeField(label='Время рассылки', required=False,
                                   widget=forms.TimeInput(attrs={'class': 'same-widht'}))
    mailing_period = forms.ChoiceField(label='Период рассылки', required=False, choices=(
        (None, 'Весь день'),
        ('PD', 'Раз в сутки'),
        ('PW', 'Раз в неделю'),
        ('PM', 'Раз в месяц')), widget=forms.Select(attrs={'class': 'same-widht'}))
    mailing_status = forms.ChoiceField(
        label='Статус рассылки',
        initial=('CRT', 'Создана'),
        choices=(
            ('CNL', 'Завершена'),
            ('CRT', 'Создана'),
            ('ACT', 'Запущена')),
        widget=forms.Select(
            attrs={
                'class': 'same-widht'
            }
        )
    )
    mailing_day = forms.ChoiceField(
        label='День рассылки',
        required=False,
        choices=(
            (None, 'Каждый день'),
            ('mon', 'Понедельник'),
            ('tue', 'Вторник'),
            ('wed', 'Среда'),
            ('thu', 'Четверг'),
            ('fri', 'Пятница'),
            ('sat', 'Суббота'),
            ('sun', 'Воскресенье')),
        widget=forms.Select(
            attrs={
                'class': 'same-widht'
            }
        )
    )
    mailing_day_of_month = forms.IntegerField(
        max_value=31,
        label='День в месяце',
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'same-widht'
            }
        )
    )
    mail_header = forms.CharField(
        label='Тема письма',
        widget=forms.TextInput(
            attrs={
                'class': 'same-widht'
            }
        )
    )
    mail_message = forms.CharField(
        label='Текст письма',
        widget=forms.Textarea(
            attrs={
                'class': 'same-widht same-height'
            }
        )
    )
    recepient = forms.ModelMultipleChoiceField(
        label='Адресанты',
        queryset=m.Clients.objects.all(),
        widget=forms.SelectMultiple(
            attrs={
                'class': 'same-widht'
            }
        )
    )

    class Meta:
        model = m.Mailing
        exclude = ['mailing_author']


class ClientsForm(forms.ModelForm):
    email = forms.CharField(
        max_length=200,
        label='Электронная почта',
        widget=forms.TextInput(
            attrs={
                'class': 'same-widht'
            }
        )
    )
    name = forms.CharField(
        max_length=200,
        label='Имя',
        widget=forms.TextInput(
            attrs={
                'class': 'same-widht'
            }
        )
    )
    surame = forms.CharField(
        max_length=200,
        label='Фамилия',
        widget=forms.TextInput(
            attrs={
                'class': 'same-widht'
            }
        )
    )
    fathers_name = forms.CharField(
        max_length=200,
        label='Отчество',
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'same-widht'
            }
        )
    )
    comment = forms.Field(
        label='Комментарий',
        widget=forms.Textarea(
            attrs={
                'class': 'same-widht same-height'
            }
        )
    )

    class Meta:
        model = m.Clients
        exclude = ['client_author']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data['email']
        if '@' not in email and '.' not in email:
            raise forms.ValidationError('Это не эмейл, чувак')
        return email

service_app/views.py
import random
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic as g

from service_app import models as m
from blog_app import models as blog_models
from service_app import forms as f
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

class IndexListView(g.ListView):
    model = m.Mailing
    template_name = 'service_app/index_list.html'
    context_object_name = 'context'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mailings_count'] = len(m.Mailing.objects.filter(mailing_author=self.request.user))
        context['active_mailings_count'] = len(
            m.Mailing.objects.filter(mailing_status='ACT').filter(mailing_author=self.request.user))
        context['unique_clients'] = len(m.Clients.objects.filter(client_author=self.request.user))
        context['random_post'] = self.get_random_records()
        return context

    @staticmethod
    def get_random_records():
        # Получаем общее количество записей в модели
        total_records = blog_models.Blog.objects.count()

        # Если в модели менее трех записей, выбираем все записи
        if total_records <= 3:
            random_records = blog_models.Blog.objects.all()
        else:
            # Генерируем случайные индексы записей
            random_indexes = random.sample(range(total_records), 3)

            # Выбираем три записи с соответствующими индексами
            random_records = blog_models.Blog.objects.filter(pk__in=random_indexes)
        return random_records

    def get_queryset(self):
        queryset = super().get_queryset()
        user = self.request.user
        if user.is_authenticated:
            if user.is_staff or user.is_superuser:
                pass
            else:
                queryset = queryset.filter(mailing_author=self.request.user)
        return queryset


class ClientsListVew(g.ListView):
    model = m.Clients
    template_name = 'service_app/clients/clients_list.html'
    context_object_name = 'context'

    def get_queryset(self):
        queryset = super().get_queryset()
        new_query = queryset.filter(client_author=self.request.user)
        return new_query


class ClientView(g.DetailView):
    model = m.Clients
    template_name = 'service_app/clients/clients_view.html'
    context_object_name = 'context'


class ClientCreateView(LoginRequiredMixin, g.CreateView):
    model = m.Clients
    template_name = 'service_app/clients/clients_create.html'
    success_url = reverse_lazy('service_app:index')
    form_class = f.ClientsForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["editing"] = False
        return context

    def form_valid(self, form):
        if form.is_valid():
            w = form.save(commit=False)
            w.client_author = self.request.user
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, g.UpdateView):
    model = m.Clients
    template_name = 'service_app/clients/clients_create.html'
    form_class = f.ClientsForm
    success_url = reverse_lazy('service_app:index')
    context_object_name = 'context'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["editing"] = True
        return context

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
        return super().form_valid(form)


class ClientDeleteView(LoginRequiredMixin, g.DeleteView):
    model = m.Clients
    template_name = "service_app/clients/clients_delete.html"
    context_object_name = 'context'
    success_url = reverse_lazy('service_app:clients_list')

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset.filter(pk=self.kwargs['pk'])
        return queryset


class MailingCreateView(LoginRequiredMixin, g.CreateView):
    model = m.Mailing
    template_name = "service_app/mailing/mailing_create.html"
    success_url = reverse_lazy("service_app:index")
    form_class = f.MailerForm
    context_object_name = 'context'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["editing"] = False
        return context

    def form_valid(self, form):
        if form.is_valid():
            w = form.save(commit=False)
            w.mailing_author = self.request.user
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        # Добавление дополнительных аргументов для формы
        kwargs['user'] = self.request.user.email
        return kwargs


class MailingUpdateView(LoginRequiredMixin, g.UpdateView):
    model = m.Mailing
    template_name = "service_app/mailing/mailing_create.html"
    success_url = reverse_lazy("service_app:index")
    form_class = f.MailerForm
    context_object_name = 'context'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["clients"] = m.Clients.objects.all()
        context["editing"] = True
        return context

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # Передача пользователя в `kwargs`
        return kwargs


class MailingView(g.DetailView):
    model = m.Mailing
    template_name = "service_app/mailing/mailing_view.html"
    context_object_name = 'context'


class MailingDeliteView(LoginRequiredMixin, g.DeleteView):
    model = m.Mailing
    template_name = "service_app/mailing/mailing_delete.html"
    context_object_name = 'context'
    success_url = reverse_lazy('service_app:index')

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset.filter(pk=self.kwargs['pk'])
        return queryset


# @permission_required('service_app.change_blog')
def change_mailing_status(request, pk):
    mailing = get_object_or_404(m.Mailing, pk=pk)
    if mailing.mailing_status == 'ACT':
        mailing.mailing_status = 'CNL'
    else:
        mailing.mailing_status = 'ACT'
    mailing.save()
    return redirect(reverse('service_app:index'))


class LogsListView(g.ListView):
    model = m.Logs
    template_name = 'service_app/logs_list.html'
    context_object_name = 'logs'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        user = self.request.user
        if user.is_authenticated:
            queryset = queryset.filter(log_author=user.email)
        return queryset

service_app/templates/service_app/base.html
<!doctype html>
<html lang="en" class="h-100">
    <script
        src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>

    {% load static %}

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content>
        <title>Сервис для создания рассылок!</title>

        <link rel="canonical"
            href="https://getbootstrap.com/docs/5.0/examples/cover/">

        <!-- Bootstrap core CSS -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

        <style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
        font-size: 3.5rem;
        }
    }
    </style>

    </head>
    <body class="text-center text-white" style="background-color: rgb(22, 22, 22);">

        <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
            <header class="mb-auto">
                <div style="position: absolute; left: 2mm; top: 2mm;">
                    <a href="{% url 'service_app:index' %}" class="text-white" style="font-size: 6mm;"> Рассыльник</a>
                </div>
                <div style="position: absolute; right: 5mm;">
                    {% if not user.is_authenticated %}
                        <div class="row">
                            <div class="col">
                                <a href="{% url 'user_app:register_user' %}" class="card-link">Регистрация</a>
                            </div>
                            <div class="col">
                                <a href="{% url 'user_app:login_user' %}" class="card-link">Вход</a>
                            </div>
                        </div>
                    {% else %}
                        <div class="row">
                            <div class="col" style="font-size: 6mm; font-weight: bold; display: grid; place-items: end;">
                                <a href="{% url 'user_app:profile_view' %}" class="card-link col">{{ user.first_name }}</a>
                            </div>

                            <div class="col" style="font-size: 6mm; font-weight: bold; display: grid; place-items: end;">
                                <a href="{% url 'user_app:logout_user' %}" class="card-link col">Выход</a>
                            </div>
                        </div>
                    {% endif %}
                </div>
                    
                    {% if user.is_authenticated %}
                        {% if user.is_staff %}
                        <div class="row mb-3 text-end" style="position: relative; top: 10mm; left: 75%;">
                            <a type="button" class="btn btn-outline-light col-1" style="font-size: 5mm;" href="{% url 'user_app:users_list' %}">Пользователи</a>
                            <a type="button" class="btn btn-outline-light col-1" style="font-size: 5mm;" href="{% url 'service_app:clients_list' %}">Адресанты</a>
                            <a type="button" class="btn btn-outline-light col-1" style="font-size: 5mm;" href="{% url 'blog_app:all_posts' %}">Блог</a>
                        </div>
                        {% else %}
                            <div class="row mb-3 text-end" style="position: relative; top: 10mm; left: 84%;">
                                <a type="button" class="btn btn-outline-light col-1" style="font-size: 5mm;" href="{% url 'service_app:clients_list' %}">Адресанты</a>
                                <a type="button" class="btn btn-outline-light col-1" style="font-size: 5mm;" href="{% url 'blog_app:all_posts' %}">Блог</a>
                            </div>
                        {% endif %}
                    {% else %}
                        <div class="row mb-3 text-end" style="position: relative; top: 10mm; left: 92%;">
                            <a type="button" class="btn btn-outline-light col-1" style="font-size: 5mm;" href="{% url 'blog_app:all_posts' %}">Блог</a>
                        </div>
                    {% endif %}
                        
                    
                    
                </div>
            </header>

            <main>

                {% block content %}

                {% endblock content %}
            </main>
        </div>
    </body>
</html>

service_app/templates/service_app/index_list.html
{% extends 'service_app/base.html' %}

{% block content %}
{% load mediapath %}

{% if user.is_authenticated %}
    <h1>Список рассылок</h1>
<p class="lead">Ниже представлены рассылки, уже созданные</p>
<div class="container text-center">
    <div class="row justify-content-md-center">
        <div class="col col-lg-2">
            <a type="button" class="btn btn-outline-light"
                href="{% url 'service_app:create_client' %}">Создать клиента</a>
        </div>
        <div class="col-md-auto">
            <a type="button" class="btn btn-outline-light"
                href="{% url 'service_app:create_mailer' %}">Создать рассылку</a>
        </div>
        <div class="col col-lg-2">
            <a type="button" class="btn btn-outline-light" href="{% url 'service_app:logs_view' %}">Просмотреть логи</a>
        </div>
    </div>
{% else %}
<h1>Создай свою рассылку!</h1>
{% endif %}
    

</div>

<div style="width: 20cm; height: 10; position: relative; left: 150mm; top: 8mm;" class="mb-5">
<div id="carouselExampleDark" class="carousel carousel-dark slide">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active"
            aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        {% for post in random_post %}            
            <div class="carousel-item active" data-bs-interval="10000">
                <div style="position: absolute; top: 5mm; right: 5mm; z-index: 101;">
                    <a type="button" href="{% url 'blog_app:view' post.pk %}" class="btn btn-outline-light">Читать</a>
                </div>
                
                {% if post.preview %}
                    <img src="{% mediapath post.preview %}" class="d-block" style="width: 100%; height: 10cm;" alt="Превью">
                {% else %}
                    <img src="../../../media/without_picture.jpg" class="d-block" style="width: 100%; height: 10cm;" alt="Превью">
                {% endif %}
                    
                <div class="carousel-caption d-none d-md-block text-white">
                    <h5>{{ post.title }}</h5>
                    <p>{{ post.content|truncatechars:100 }}</p>
                </div>
            </div>        
        {% endfor %}
    </div>

    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden" style="z-index: 80;">Предыдущая запись</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden" style="z-index: 80;">Следующая запись</span>
    </button>
</div>

</div>
{% if not user.is_authenticated %}
    <h2>Зарегистрируйтесь для создания рассылки</h2>
{% else %}

    <div class="row col-8 mb-4 text-center" 
    style="position: relative; top: 1cm; left: 85mm;
    font-size: 5mm;">
        <div class="col">Всего рассылок: {{ mailings_count }}</div>
        <div class="col">Активных рассылок: {{ active_mailings_count }}</div>
        <div class="col">Уникальных клиентов для рассылки: {{ unique_clients }}</div>
    </div>

    <div class="container text-center" style="position: relative; top: 12mm;">
        <div class="row justify-content-md-center">
            <div class="col">
                {% for c in context %}
                <div class="card text-white text-bg-dark mb-4" 
                style="position: relative; left: 65mm; width: 50rem; height: auto;">
                    <div class="row">
                        <div class="col text-start"><h5 class="card-header">{{ c.get_mailing_status_display }}</h5></div>
                        
                        {% if c.mailing_time %}
                            <div class="col text-end"><h5 style="position: relative; top: 28%; font-family: monospace;">{{c.mailing_time}}</h5></div>
                        {% endif %}
                        
                        {% if c.mailing_status == 'ACT' %}
                        <div class="col text-end"><a href="{% url 'service_app:status_mailer' c.pk %}" class="btn text-white" 
                            style="position: relative; top: 2mm; right: 1mm;background-color: rgb(150, 150, 150);">Деактивировать</a></div>
                        {% else %}
                        <div class="col text-end"><a href="{% url 'service_app:status_mailer' c.pk %}" class="btn text-white"
                            style="position: relative; top: 2mm; right: 1mm;background-color: rgb(150, 150, 150);">Aктивировать</a></div>
                        {% endif %}
                    </div>
                    <div class="card-body text-start">
                        <h5 class="card-title">{{ c.mail_header }}</h5>
                        <p class="card-text" style="position: relative; top: 3mm;">{{ c.mail_message|truncatechars:150 }}</p>
                        <h6 style="position: relative; top: 3mm;">{{ c.get_mailing_period_display }}</h6>
                        <p>
                            <h6 style="position: relative; top: 3mm;">Участники рассылки:</h6>
                            <div style="position: relative; top: 3mm;">
                                <ul>
                                {% for adresant in c.recepient.all %}
                                    <li>{{ adresant.name }} {{ adresant.surame }}</li>
                                {% endfor %}
                                </ul>
                            </div>
                        </p>
                        <div class="row" style="position: relative; top: 3mm;">
                            <div class="col text-start"><a href="{% url 'service_app:view_mailer' c.pk %}" class="btn text-white" style="background-color: rgb(10, 84, 84);">Прочитать</a></div>
                            {% if user.email == c.mailing_author %}
                                <div class="col text-center">
                                    <a href="{% url 'service_app:edit_mailer' c.pk %}" class="btn text-white"
                                    style="background-color: rgb(10, 80, 84);">Редактировать</a></div>
                                <div class="col text-end">
                                    <a href="{% url 'service_app:delete_mailer' c.pk %}" class="btn text-white" 
                                    style="background-color: brown;">Удалить</a></div>
                            {% endif %}
                            
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}