blog_app/urls.py
from django.urls import path
from blog_app.apps import BlogAppConfig
from blog_app import views as v

app_name = BlogAppConfig.name


urlpatterns = [
    path('all_posts/', v.PostsListView.as_view() , name='all_posts'),
    path('create/', v.PostCreateView.as_view(), name='create'),
    path('<int:pk>/view/', v.PostDetailView.as_view() , name='view'),
    path('<int:pk>/edit/', v.PostUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', v.PostDeleteView.as_view() , name='delete'),
    path('<int:pk>/change_blog_status/', v.change_blog_status , name='change_blog_status'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('service_app.urls', 'service_app'), namespace='service_app')),
    path('blog_app/', include(('blog_app.urls', 'blog_app'), namespace='blog_app')),
    path('user_app/', include(('user_app.urls', 'user_app'), namespace='user_app')),

]

blog_app/models.py
from django.db import models


# Create your models here.
class Blog(models.Model):
    """Модель для блога нашего проекта"""
    title = models.CharField(max_length=50, verbose_name="Заголовок")
    slug = models.CharField(max_length=100, verbose_name="Slug")
    content = models.TextField(verbose_name="Содержимое")
    preview = models.ImageField(verbose_name="Превью", upload_to="catalog/media", null=True, blank=True)
    creation_date = models.DateField(auto_now=True, verbose_name="Дата сощдания")
    is_published = models.BooleanField(default=True, verbose_name="Статус публикации")
    views_counter = models.IntegerField(verbose_name="Счетчик просморов", default=0)
    post_author = models.CharField(max_length=50, verbose_name="Автор", null=True, blank=True)

    def __str__(self) -> str:
        return f"Запись {self.title} с количеством просмотров - {self.views_counter}"

    class Meta:
        verbose_name = "Блог для сайта"
        verbose_name_plural = "Блоги для сайта"

blog_app/forms.py
from django import forms as f
from blog_app import models as m


class BlogCreateForm(f.ModelForm):
    """Форма для создания / редактирования записей блога"""
    title = f.CharField(label='Заголовок', widget=f.TextInput(attrs={'class': 'my-same-widht'}))
    content = f.CharField(label='Содержимое', widget=f.Textarea(attrs={'class': 'my-big-textarea'}))
    preview = f.ImageField(label='Превью', required=False, widget=f.FileInput(attrs={
        'class': 'my-same-widht text-center'
    }))
    is_published = f.BooleanField(label='Статус публикации',widget=f.CheckboxInput(attrs={
        'class': 'my-checkbox',
        'style': 'position: relative; right: 2cm'
    }))

    class Meta:
        model = m.Blog
        fields = ['title', 'content', 'preview', 'is_published']

blog_app/views.py
from typing import Any
from django.db import models
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic as g
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import permission_required

from blog_app import models
from blog_app import forms as f

from my_util_files.transcrypter import transcription


# Create your views here.

class PostsListView(g.ListView):
    model = models.Blog
    template_name = 'blog_app/posts_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        user = self.request.user
        if user.is_authenticated:
            if user.is_staff or user.is_superuser:
                queryset = queryset.order_by('views_counter').reverse()
            else:
                queryset = queryset.filter(is_published=True).order_by('views_counter').reverse() | queryset.filter(
                    post_author=user).order_by('views_counter').reverse()
        else:
            queryset = queryset.filter(is_published=True).order_by('views_counter').reverse()
        return queryset


class PostCreateView(LoginRequiredMixin, g.CreateView):
    model = models.Blog
    template_name = 'blog_app/post_create.html'
    form_class = f.BlogCreateForm
    success_url = reverse_lazy('blog_app:all_posts')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["editing"] = False
        return context

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = transcription(new_post.title)
            new_post.save()

            w = form.save(commit=False)
            w.post_author = self.request.user.email
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, g.UpdateView):
    model = models.Blog
    template_name = "blog_app/post_create.html"
    form_class = f.BlogCreateForm
    success_url = reverse_lazy('blog_app:all_posts')

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset.filter(pk=self.kwargs['pk'])
        return queryset

    def get_success_url(self) -> str:
        return reverse('blog_app:view', args=[self.kwargs.get('pk')])

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = transcription(new_post.title)
            new_post.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["editing"] = True
        return context


class PostDetailView(g.DeleteView):
    model = models.Blog
    template_name = "blog_app/post_view.html"
    context_object_name = 'post_data'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset.filter(pk=self.kwargs["pk"])
        return queryset

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_counter += 1
        self.object.save()
        return self.object

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post = transcription(new_post.title)
            print(new_post)
            new_post.save()
        return super().form_valid(form)


class PostDeleteView(LoginRequiredMixin, g.DeleteView):
    model = models.Blog
    template_name = "blog_app/post_delete.html"
    context_object_name = 'post_data'
    success_url = reverse_lazy('blog_app:all_posts')

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset.filter(pk=self.kwargs["pk"])
        return queryset


@permission_required('blog_app.change_blog')
def change_blog_status(request, pk):
    blog = get_object_or_404(models.Blog, pk=pk)
    if blog.is_published:
        blog.is_published = False
    else:
        blog.is_published = True
    blog.save()
    return redirect(reverse_lazy('blog_app:all_posts'))

blog_app/templates/blog_app/login.html
{% extends 'service_app/base.html' %}


{% block content %}
    <h1 class="text-center">Вход на сайт</h1>

    <div class="text-start col-7" style="position: absolute; grid-area: auto;">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn">Войти</button>
        </form>
    </div>
{% endblock content %}
    

blog_app/templates/blog_app/post_create.html
{% extends 'service_app/base.html' %}
{% load static %}


{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/my_styles.css' %}">
<div class="container">
    <h2 class="text-center mb-7">Создание новой записи в блоге</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col md-4 mb-2" style="position: relative; top: 1cm;">
            {% for f in form %}
                <div class="row mb-4">
                    <div class="col text-start" style="position: relative; left: 8cm;">
                        <label for="f.id_for_label" style="font-size: 5mm;">{{ f.label }}</label>
                    </div>
                    <div class="col" style="z-index: 100;">{{ f }}</div> 
                </div>
            {% endfor %}
                
            <div class="md-4 mb-4" style="position: relative;">
                {% if editing %}
                    <button type="submit" class="btn btn-primary">Изменить запись</button>
                {% else %}
                    <button type="submit" class="btn btn-primary">Добавить запись</button>
                {% endif %}
            </div>
        </div>
    </form>
</div>

{% endblock content %}

blog_app/templates/blog_app/post_delete.html
{% extends 'service_app/base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    <div class="col">
        <div class="container justify-content-center">
            <h2 align="center">Вы, действительно, хотите удалить запись?</h2>
            <div align="center"><h5>{{ post_data.title }}</h5></div>
            <h1> </h1>
        </div>
    </div>
    {{ form }}
    <div class="container text-center" style="position: relative; top: 2cm;">
        <div class="row col-6" style="position: relative; left: 25%;">
            <div class="col"><input type="submit" class="btn btn-outline-danger" value="Подтвердить"></div>
            <div class="col"><a type="button" class="btn btn-outline-success" href="{% url 'blog_app:all_posts' %}">Отменить</a></div>
        </div>
    </div>
</form>

{% endblock content %}

blog_app/templates/blog_app/post_view.html
{% extends 'service_app/base.html' %}

{% block content %}
{% load paragrapher %}

<div class="col-3 text-start" style="position: relative; top: 1cm; left: 10mm;">
    <a type="button" class="btn btn-outline-success" href="{% url 'blog_app:all_posts' %}">Вернуться к просмотру</a>
</div>
<div class="container text-left">
    <div class="col">
        <div class="row my-3">
            <div class="col mb-2">
                <div class="card-title">
                    <div align="center"> <h3>{{ post_data.title }}</h3> </div>
                </div>
                <div class="card-body text-start">
                    {% autoescape off %}            
                    <p class="fw-light">{{ post_data.content|paragrapher }}</p>     
                    {% endautoescape %}        
                </div>
            </div>
        </div>
        <div class="row my-3">
            <div class="col text-start">
                <div class="row"><h5>Количество просмотров: {{ post_data.views_counter }}</h5></div>
                
                {% if post_data.post_author != None and post_data.post_author != '' %}
                    <div class="row"><h5>Автор поста: {{ post_data.post_author }}</h5></div>
                {% endif %}

            </div>
        </div>
    </div>
</div>    

{% endblock content %}

blog_app/templates/blog_app/posts_list.html
{% extends 'service_app/base.html' %}

{% block content %}
{% load mediapath %}

<h3 align="center">Здоровье в еде!</h3>


{% if user.is_authenticated %}
    <div class="d-grid gap-2 col-6 mx-auto">
        <a class="btn btn-primary" type="button" href="{% url 'blog_app:create' %}" style="position: relative; top: 1cm;" >Добавить запись</a>
    </div>
{% endif %}

<div class="album" style="position: relative; top: 1cm;">
    <div class="container text-center">
        <div class="row row row-cols-3" style="position: relative; top: 1cm;">
            {% for card in object_list %}
            <div class="col md-3 mb-3">
                <div style="width: 20rem; height: 30rem; background-color: rgb(31, 31, 31);">
                    <div style="position: relative; top: 1px;">                        
                        {% if user.is_staff or user.is_superuser %}
                            {% if card.is_published %}
                                <a href="{% url 'blog_app:change_blog_status' card.pk %}" class="btn btn-primary btn-sm">Снять с пyбликации</a>
                            {% else %}
                                <a href="{% url 'blog_app:change_blog_status' card.pk %}" class="btn btn-primary btn-sm">Вернуть в публикацию</a>
                            {% endif %}
                        {% endif %}
                    </div>

                    {% if  card.preview%}
                        <img src="{% mediapath card.preview %}" style="height: 250px; width: 300;" class="card-img-top"
                        alt="Превью">
                    {% else %}
                        <img src="../../../media/without_picture.jpg" style="height: 250px; width: 300px;" class="card-img-top"
                            alt="Превью">
                    {% endif %}
                    
                    <div class="card-body">
                        <h5 class="card-title">{{ card.title }}</h5>
                        <p class="card-text">{{ card.content|truncatechars:60 }}</p>
                        
                    </div>
                    <div class="card-footer">
                        {% if user.email != card.post_author or user.is_authenticated == False %}
                            <a href="{% url 'blog_app:view' card.pk %}" class="btn btn-primary">Читать</a>
                        {% else %}
                            <a href="{% url 'blog_app:view' card.pk %}" class="btn btn-primary">Читать</a>
                            <a href="{% url 'blog_app:edit' card.pk %}"class="btn btn-primary">Изменить</a>
                            <a href="{% url 'blog_app:delete' card.pk %}"class="btn btn-danger">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}